# Generated by Django 5.2.4 on 2025-09-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medkitapp', '0006_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
